export const CHANGE_PRICE = "CHANGE_PRICE";
export const ADD_TAGS = "ADD_TAGS";
export const DELETE_TAGS = "DELETE_TAGS";

export const LIST_FETCH_SUCCEEDED = "LIST_FETCH_SUCCEEDED";
export const LIST_FETCH_FAILED = "LIST_FETCH_FAILED";
export const LIST_FETCH_REQUESTED = "LIST_FETCH_REQUESTED";
